### ISSUE TITLE
Can not get a output

### ISSUE THREAD

**Issue by GrunleyBIM** [OhmSweetOhm/CobieQcReporter#12]
I am having an issue getting an output.  The file looks like it runs looking at the command line and log seems to stop.  Nothing is telling be what I am missing.  I have looked through the guide book and can't figure out what I am doing wrong.  Any ideas?

**Comment by GrunleyBIM** [comment]
[crankycobiefile_v1.xlsx](https://github.com/OhmSweetOhm/CobieQcReporter/files/2921418/crankycobiefile_v1.xlsx)
[Log-Design.txt](https://github.com/OhmSweetOhm/CobieQcReporter/files/2921419/Log-Design.txt)
![qccommandlinescreenshot](https://user-images.githubusercontent.com/48140665/53672225-91efb700-3c4f-11e9-92d8-99e920822c64.JPG)

here are all the files and returns I am getting from the running the batch file

**Comment by GrunleyBIM** [comment]
I have a feeling I am missing something obvious but just can't see it

**Comment by StewartGH1970** [comment]
1. ok check you have the latest java installed
2. see attached image for all files that should be located in your CobieQcReporter folder - note \test\cobie-test.xlsx is what you need to override with your cobie export before you run either of the TestDesign.bat or TestConstruction.bat - maybe best to just download a fresh copy
3. see attached error report file of your crankycobiefile_v1.xlsx - took approx 1 min to complete due to the number of attributes you have
4. some comments on your COBie Export:
a- COBie.Type.Manufacture, Type.WarrantyGuarantorParts, Type.WarrantyGuarantorLabor must be an email address found in COBie.Contact.Email
b- looks like there are some Types & Spaces missing from a few Components ie they are noted in COBie.Component.TypeName & COBie.Component.Space but they dont exist in COBie.Type.Name or COBie.Space.Name
c- a few things to sort out in system mainly because COBie.Component.Name are missing unique names
d- Attribute sheet has errors in both SheetName & RowName again mostly due to missing unique names

hope this helps
![crankcobiefile_v1 cobieqcreport](https://user-images.githubusercontent.com/3512121/53681319-c1e69b00-3cdf-11e9-8351-1a7d75120b98.JPG)
![cobieqcreportfolder](https://user-images.githubusercontent.com/3512121/53681320-c1e69b00-3cdf-11e9-91e8-6d6be7e44d61.JPG)

**Comment by GrunleyBIM** [comment]
Thank you for responding!  I will go through what I just tried

  1.  Installed fresh version and up to date.
  2.  Installed new version, confirmed everything is in folder per screen shot.
So you got an output?  Still don’t get the html report.  I turned off my firewall (windows defender) thinking that blocking it and tried a different computer, no results. Seems to take a minute to run.

Thoughts?

Regards,
Andy

**Comment by StewartGH1970** [comment]
What about java?

**Comment by GrunleyBIM** [comment]
Just tried two different machines with fresh installs.   One had an old java the other no installed java.  No modifications to java, stock install, and it didn't run, same results. One was my wife's laptop with no corporate IT connected. Other was my work laptop. So work tower and laptop failed, home computer failed.

What are the open/close states.  So do I need to modify them from the stock install?


Thanks
Andy


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by StewartGH1970** [comment]
Not sure what you mean by open/closes states?

All you do is
1- download zip and extract to desktop
2- copy cobie export to test folder make sure you override the test file
3- double click the testdesign.bat
4- open up testdesign.html 

If the above doesn't work then pass as not had any previous issues before

**Comment by GrunleyBIM** [comment]
I was referring to your cobie comment about java states.  I am doing exactly what you are describing below to run it.

Using java version 8.201 fyi.  Is that correct?



Sent from my Verizon, Samsung Galaxy smartphone

**Comment by StewartGH1970** [comment]
Will check later what version i have but i always update when noted so should be the same aa you. Maybe head over to the COBie group on linkedin to ask Bill East for further advice
