### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by kat-mcleod** [OhmSweetOhm/CobieQcReporter#16]
I'm struggling with Out of Memory Errors when trying to use the tool. More than half of the files I try to check now won't work. The file in this example is 1.9MB with the largest tab having 12k rows.

Using Java version 8 Update 161 (build 1.8.0_161-b12)

Is there anything I can do to get these files through the tool? I had been deleting the coordinates/attribute and sometimes system rows in order to get the file through the tool but I now have some where even the component tab is too big for the file to run.

![image](https://user-images.githubusercontent.com/82871083/115364551-69becb80-a1bb-11eb-8fe9-d73e8bfcca25.png)

**Comment by LukasClark** [comment]
Hi, I wanted to mention I am having the same problem! Any help would be much appreciated. Thank you

**Comment by OhmSweetOhm** [comment]
Hi,

This problem is fairly common for larger models due to the data structures used to store COBie data in memory for the checking process. While your computer may have sufficient memory to execute the QC Checker and check the model, your Java Virtual Machine (JVM) is not given access to the entire pool of memory on your computer. The default amount of memory that a JVM received depends on a variety of factors.

To fix the noted issue, you need to tell Java.exe to utilize more Heap Space when running the QC Checker. The way to accomplish this is as follows:

When you execute your command line to run the QC Checker, add an additional argument called Xmx to increase the maximum heap size (see https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html and https://www.baeldung.com/jvm-parameters).  Here is an example usage of the Xmx argument for the QC Checker to provide up to 1GB of memory to the JVM...

java -Xmx1G -jar CobieQCReporter.jar -i model.xlsx -o BLD3 -p c

The amount of memory you should pass in is somewhat a matter of trial and error based on your model size. I used to be able to tell a more precise calculation based on the number of rows, but I am not sure where to find that technical information anymore. Be careful though not to pass in more memory than your computer has or more memory than your computer could use and still remain stable. I'd advise not to allocate more than 50-75% of your memory under a light load just to be sure that the Operating System can function efficiently.

Please let me know if this fixes your issues.

**Comment by kat-mcleod** [comment]
@OhmSweetOhm I'eve tested this on my largest excel output and the tool has been able to run the checks. Thank you!
